#!/bin/bash
# modules/05-hostname.sh - Настройка hostname и /etc/hosts
# Часть Mail Server Deployment Module System

# Загрузка утилит (если ещё не загружены)
[[ -z "${UTIL_PRINT_LOADED}" ]] && source ./utils/print.sh 2>/dev/null
[[ -z "${UTIL_LOGGING_LOADED}" ]] && source ./utils/logging.sh 2>/dev/null
[[ -z "${UTIL_FUNCTIONS_LOADED}" ]] && source ./utils/functions.sh 2>/dev/null


# --- Загружаем конфиг, если нужно ---
load_config || {
    print_error "Не удалось загрузить конфигурацию. Убедитесь, что ./config/main.conf существует и содержит DOMAIN, SERVER_IP."
    log_error "Failed to load required configuration"
    [[ "$FORCE_MODE" != "true" ]] && exit 1
}

# --- Проверка: переменные теперь точно заданы? ---
print_step "Проверка необходимых переменных: DOMAIN, SERVER_IP"
if [[ -z "$DOMAIN" ]]; then
    print_error "Переменная DOMAIN не задана (даже после загрузки конфига)"
    log_error "DOMAIN is not set after config load"
    [[ "$FORCE_MODE" != "true" ]] && exit 1
fi

if [[ -z "$SERVER_IP" ]]; then
    print_error "Переменная SERVER_IP не задана (даже после загрузки конфига)"
    log_error "SERVER_IP is not set after config load"
    [[ "$FORCE_MODE" != "true" ]] && exit 1
fi

# --- Основная логика модуля ---
print_info "Текущие настройки хоста:"
hostnamectl 2>/dev/null | grep -E "(Static|Pretty|Transient)" || true

print_step "Установка системного hostname: srv.$DOMAIN"
if hostnamectl set-hostname "srv.$DOMAIN" 2>/dev/null; then
    print_success "Hostname установлен: srv.$DOMAIN"
    log_info "System hostname set to: srv.$DOMAIN"
else
    print_error "Не удалось установить hostname"
    log_error "Failed to set system hostname"
    [[ "$FORCE_MODE" != "true" ]] && exit 1
fi

print_step "Установка pretty hostname: 'Mail Server'"
if hostnamectl set-hostname "Mail Server" --pretty 2>/dev/null; then
    print_success "Pretty hostname установлен"
    log_info "Pretty hostname set to: Mail Server"
else
    print_warning "Не удалось установить pretty hostname (не критично)"
    log_warn "Failed to set pretty hostname (non-critical)"
fi

print_step "Настройка файла /etc/hosts"

# Создаем резервную копию
cp /etc/hosts /etc/hosts.bak."$(date +%Y%m%d_%H%M%S)" 2>/dev/null && \
    log_info "Backup of /etc/hosts created"

# Формируем новый файл
{
    echo "# Generated by mail server installer"
    echo "127.0.0.1 localhost"
    echo "127.0.1.1 srv.$DOMAIN srv"
    echo "$SERVER_IP $DOMAIN mail.$DOMAIN www.$DOMAIN"
} > /etc/hosts.new

# Проверяем, что запись корректна (SERVER_IP должен быть валидным IP)
if [[ ! "$SERVER_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    print_warning "SERVER_IP '$SERVER_IP' не похож на IPv4 — проверьте вручную"
    log_warn "SERVER_IP '$SERVER_IP' does not look like IPv4"
fi

# Применяем новый файл
mv /etc/hosts.new /etc/hosts && \
    print_success "Файл /etc/hosts обновлён" && \
    log_info "/etc/hosts updated successfully"

print_step "Текущее содержимое /etc/hosts:"
cat /etc/hosts
log_info "Current /etc/hosts content displayed"

# Проверка: убедимся, что имя разрешается
print_step "Проверка разрешения имени srv.$DOMAIN"
if ping -c 1 "srv.$DOMAIN" >/dev/null 2>&1; then
    print_success "Имя srv.$DOMAIN успешно разрешается"
    log_info "Hostname srv.$DOMAIN resolves correctly"
else
    print_warning "Имя srv.$DOMAIN не разрешается — проверьте /etc/hosts"
    log_warn "Hostname srv.$DOMAIN does not resolve locally"
fi
